apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: django_demo
  name: django_demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django_demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: django_demo
    spec:
      containers:
      - image: gamertech1/django-app:11
        name: django_demo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: django_demo
